# @package _global_

defaults:
  - _self_
  - data: cctv
  - model: unet
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ./checkpoints/last.ckpt
